// Code generated by MockGen. DO NOT EDIT.
// Source: internal/entry/http_handle.go
//
// Generated by this command:
//
//	mockgen -source=internal/entry/http_handle.go -destination=mocks/mockentry/mock_http_handle.go -package=mockentry
//

// Package mockentry is a generated GoMock package.
package mockentry

import (
	context "context"
	reflect "reflect"

	orchestrator "github.com/IsaacDSC/sagaflow/internal/orchestrator"
	gomock "go.uber.org/mock/gomock"
)

// MockOrchestrator is a mock of Orchestrator interface.
type MockOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorMockRecorder
	isgomock struct{}
}

// MockOrchestratorMockRecorder is the mock recorder for MockOrchestrator.
type MockOrchestratorMockRecorder struct {
	mock *MockOrchestrator
}

// NewMockOrchestrator creates a new mock instance.
func NewMockOrchestrator(ctrl *gomock.Controller) *MockOrchestrator {
	mock := &MockOrchestrator{ctrl: ctrl}
	mock.recorder = &MockOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestrator) EXPECT() *MockOrchestratorMockRecorder {
	return m.recorder
}

// Transaction mocks base method.
func (m *MockOrchestrator) Transaction(ctx context.Context, txInput orchestrator.Input) (map[string]orchestrator.DataAggregator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, txInput)
	ret0, _ := ret[0].(map[string]orchestrator.DataAggregator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transaction indicates an expected call of Transaction.
func (mr *MockOrchestratorMockRecorder) Transaction(ctx, txInput any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockOrchestrator)(nil).Transaction), ctx, txInput)
}
