// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/connector/http.go
//
// Generated by this command:
//
//	mockgen -source=pkg/connector/http.go -destination=mocks/mockconnector/mock_http.go -package=mockconnector
//

// Package mockconnector is a generated GoMock package.
package mockconnector

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResponse is a mock of Response interface.
type MockResponse struct {
	ctrl     *gomock.Controller
	recorder *MockResponseMockRecorder
	isgomock struct{}
}

// MockResponseMockRecorder is the mock recorder for MockResponse.
type MockResponseMockRecorder struct {
	mock *MockResponse
}

// NewMockResponse creates a new mock instance.
func NewMockResponse(ctrl *gomock.Controller) *MockResponse {
	mock := &MockResponse{ctrl: ctrl}
	mock.recorder = &MockResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponse) EXPECT() *MockResponseMockRecorder {
	return m.recorder
}

// BodyBytes mocks base method.
func (m *MockResponse) BodyBytes() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BodyBytes")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// BodyBytes indicates an expected call of BodyBytes.
func (mr *MockResponseMockRecorder) BodyBytes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BodyBytes", reflect.TypeOf((*MockResponse)(nil).BodyBytes))
}

// Code mocks base method.
func (m *MockResponse) Code() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code")
	ret0, _ := ret[0].(int)
	return ret0
}

// Code indicates an expected call of Code.
func (mr *MockResponseMockRecorder) Code() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code", reflect.TypeOf((*MockResponse)(nil).Code))
}

// Data mocks base method.
func (m *MockResponse) Data() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].(any)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockResponseMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockResponse)(nil).Data))
}

// Write mocks base method.
func (m *MockResponse) Write(w http.ResponseWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockResponseMockRecorder) Write(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockResponse)(nil).Write), w)
}
