// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/psql.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/psql.go -destination=mocks/mockstore/mock_psql.go -package=mockstore
//

// Package mockstore is a generated GoMock package.
package mockstore

import (
	context "context"
	reflect "reflect"

	rule "github.com/IsaacDSC/sagaflow/internal/rule"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPsqlImpl is a mock of PsqlImpl interface.
type MockPsqlImpl struct {
	ctrl     *gomock.Controller
	recorder *MockPsqlImplMockRecorder
	isgomock struct{}
}

// MockPsqlImplMockRecorder is the mock recorder for MockPsqlImpl.
type MockPsqlImplMockRecorder struct {
	mock *MockPsqlImpl
}

// NewMockPsqlImpl creates a new mock instance.
func NewMockPsqlImpl(ctrl *gomock.Controller) *MockPsqlImpl {
	mock := &MockPsqlImpl{ctrl: ctrl}
	mock.recorder = &MockPsqlImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPsqlImpl) EXPECT() *MockPsqlImplMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockPsqlImpl) FindAll(ctx context.Context) ([]rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPsqlImplMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPsqlImpl)(nil).FindAll), ctx)
}

// Save mocks base method.
func (m *MockPsqlImpl) Save(ctx context.Context, arg1 rule.Rule) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockPsqlImplMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPsqlImpl)(nil).Save), ctx, arg1)
}
