// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/psql.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/psql.go -destination=mocks/mockstore/mock_psql.go -package=mockstore
//

// Package mockstore is a generated GoMock package.
package mockstore

import (
	context "context"
	reflect "reflect"

	orchestrator "github.com/IsaacDSC/sagaflow/internal/orchestrator"
	rule "github.com/IsaacDSC/sagaflow/internal/rule"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPsqlImpl is a mock of PsqlImpl interface.
type MockPsqlImpl struct {
	ctrl     *gomock.Controller
	recorder *MockPsqlImplMockRecorder
	isgomock struct{}
}

// MockPsqlImplMockRecorder is the mock recorder for MockPsqlImpl.
type MockPsqlImplMockRecorder struct {
	mock *MockPsqlImpl
}

// NewMockPsqlImpl creates a new mock instance.
func NewMockPsqlImpl(ctrl *gomock.Controller) *MockPsqlImpl {
	mock := &MockPsqlImpl{ctrl: ctrl}
	mock.recorder = &MockPsqlImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPsqlImpl) EXPECT() *MockPsqlImplMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockPsqlImpl) FindAll(ctx context.Context) ([]rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPsqlImplMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPsqlImpl)(nil).FindAll), ctx)
}

// GetTransactions mocks base method.
func (m *MockPsqlImpl) GetTransactions(ctx context.Context, status string) ([]orchestrator.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, status)
	ret0, _ := ret[0].([]orchestrator.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockPsqlImplMockRecorder) GetTransactions(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockPsqlImpl)(nil).GetTransactions), ctx, status)
}

// Save mocks base method.
func (m *MockPsqlImpl) Save(ctx context.Context, arg1 rule.Rule) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockPsqlImplMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPsqlImpl)(nil).Save), ctx, arg1)
}

// SaveTransaction mocks base method.
func (m *MockPsqlImpl) SaveTransaction(ctx context.Context, txData orchestrator.Transaction, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTransaction", ctx, txData, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTransaction indicates an expected call of SaveTransaction.
func (mr *MockPsqlImplMockRecorder) SaveTransaction(ctx, txData, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTransaction", reflect.TypeOf((*MockPsqlImpl)(nil).SaveTransaction), ctx, txData, errorMessage)
}

// UpdateTransaction mocks base method.
func (m *MockPsqlImpl) UpdateTransaction(ctx context.Context, txID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", ctx, txID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockPsqlImplMockRecorder) UpdateTransaction(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockPsqlImpl)(nil).UpdateTransaction), ctx, txID)
}
