// Code generated by MockGen. DO NOT EDIT.
// Source: internal/store/mem.go
//
// Generated by this command:
//
//	mockgen -source=internal/store/mem.go -destination=mocks/mockstore/mock_mem.go -package=mockstore
//

// Package mockstore is a generated GoMock package.
package mockstore

import (
	context "context"
	reflect "reflect"

	rule "github.com/IsaacDSC/sagaflow/internal/rule"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMemoryImpl is a mock of MemoryImpl interface.
type MockMemoryImpl struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryImplMockRecorder
	isgomock struct{}
}

// MockMemoryImplMockRecorder is the mock recorder for MockMemoryImpl.
type MockMemoryImplMockRecorder struct {
	mock *MockMemoryImpl
}

// NewMockMemoryImpl creates a new mock instance.
func NewMockMemoryImpl(ctrl *gomock.Controller) *MockMemoryImpl {
	mock := &MockMemoryImpl{ctrl: ctrl}
	mock.recorder = &MockMemoryImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryImpl) EXPECT() *MockMemoryImplMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockMemoryImpl) Find(ctx context.Context, txID uuid.UUID) (rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, txID)
	ret0, _ := ret[0].(rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockMemoryImplMockRecorder) Find(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMemoryImpl)(nil).Find), ctx, txID)
}

// Refresh mocks base method.
func (m *MockMemoryImpl) Refresh(ctx context.Context, rules []rule.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, rules)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockMemoryImplMockRecorder) Refresh(ctx, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockMemoryImpl)(nil).Refresh), ctx, rules)
}
