// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=../../mocks/mockgqueue/mock_api.go -package=mockgqueue
//

// Package mockgqueue is a generated GoMock package.
package mockgqueue

import (
	context "context"
	reflect "reflect"

	gqueue "github.com/IsaacDSC/sagaflow/pkg/gqueue"
	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockAPI) Publish(ctx context.Context, input gqueue.PublishInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockAPIMockRecorder) Publish(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockAPI)(nil).Publish), ctx, input)
}

// UpsertEventConsumer mocks base method.
func (m *MockAPI) UpsertEventConsumer(ctx context.Context, input gqueue.UpsertEventConsumerInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEventConsumer", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEventConsumer indicates an expected call of UpsertEventConsumer.
func (mr *MockAPIMockRecorder) UpsertEventConsumer(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEventConsumer", reflect.TypeOf((*MockAPI)(nil).UpsertEventConsumer), ctx, input)
}
