// Code generated by MockGen. DO NOT EDIT.
// Source: internal/nofifygate/http_client.go
//
// Generated by this command:
//
//	mockgen -source=internal/nofifygate/http_client.go -destination=mocks/mocknofifygate/mock_http_client.go -package=mocknofifygate
//

// Package mocknofifygate is a generated GoMock package.
package mocknofifygate

import (
	context "context"
	reflect "reflect"

	orchestrator "github.com/IsaacDSC/sagaflow/internal/orchestrator"
	rule "github.com/IsaacDSC/sagaflow/internal/rule"
	gomock "go.uber.org/mock/gomock"
)

// MockHttpClientImpl is a mock of HttpClientImpl interface.
type MockHttpClientImpl struct {
	ctrl     *gomock.Controller
	recorder *MockHttpClientImplMockRecorder
	isgomock struct{}
}

// MockHttpClientImplMockRecorder is the mock recorder for MockHttpClientImpl.
type MockHttpClientImplMockRecorder struct {
	mock *MockHttpClientImpl
}

// NewMockHttpClientImpl creates a new mock instance.
func NewMockHttpClientImpl(ctrl *gomock.Controller) *MockHttpClientImpl {
	mock := &MockHttpClientImpl{ctrl: ctrl}
	mock.recorder = &MockHttpClientImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpClientImpl) EXPECT() *MockHttpClientImplMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockHttpClientImpl) Send(ctx context.Context, httpCfg rule.HTTPConfig, tx orchestrator.Input, conf rule.Configs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, httpCfg, tx, conf)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockHttpClientImplMockRecorder) Send(ctx, httpCfg, tx, conf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockHttpClientImpl)(nil).Send), ctx, httpCfg, tx, conf)
}
