// Code generated by MockGen. DO NOT EDIT.
// Source: internal/orchestrator/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/orchestrator/service.go -destination=mocks/mockorchestrator/mock_service.go -package=mockorchestrator
//

// Package mockorchestrator is a generated GoMock package.
package mockorchestrator

import (
	context "context"
	reflect "reflect"

	orchestrator "github.com/IsaacDSC/sagaflow/internal/orchestrator"
	rule "github.com/IsaacDSC/sagaflow/internal/rule"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockStore) Find(ctx context.Context, txID uuid.UUID) (rule.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, txID)
	ret0, _ := ret[0].(rule.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStoreMockRecorder) Find(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStore)(nil).Find), ctx, txID)
}

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
	isgomock struct{}
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockQueue) Send(ctx context.Context, httpCfg rule.HTTPConfig, tx orchestrator.Input, conf rule.Configs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, httpCfg, tx, conf)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockQueueMockRecorder) Send(ctx, httpCfg, tx, conf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockQueue)(nil).Send), ctx, httpCfg, tx, conf)
}
